### ISSUE TITLE
ImportError: cannot import name 'app_cwd'

### ISSUE THREAD

**Issue by chihuen** [Digital-Sapphire/PyUpdater#166] opened 2019-04-05 14:06 UTC
`Traceback (most recent call last):
  File "xxxxx.py", line 8, in <module>
    from pyupdater.client import Client
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyupdater/client/__init__.py", line 38, in <module>
    from dsdev_utils.paths import app_cwd, ChDir as _ChDir
ImportError: cannot import name 'app_cwd'`

I use python3.6 to run the code but it raise an error. 
my packages version：
dsdev-utils                1.0.2  
PyUpdater                  2.5.3   
PyUpdater-s3-Plugin        3.0.6   
PyUpdater-SCP-Plugin       3.0.12

**Comment by chihuen** [comment] 2019-04-05 14:07
Could anybody plz tell me how to fix it? lol

**Comment by chihuen** [comment] 2019-04-05 14:34
ok i have found that app_cwd is in dsdev_utils.app

**Comment by webpolis** [comment] 2019-04-08 18:05
https://github.com/JMSwag/dsdev-utils/blob/e6b117aad3e1eb0ad1ff9463ec387aa8fd45a308/tests/test_app.py#L27

The package dsdev-utils has been updated and some paths were changed.

Let me know if I should submit a PR. I temporarily changed it by hand

**Comment by JMSwag** [comment] 2019-04-08 18:13
Hi all,

The master branch has been updated for the change in dsdev_utils. I’ll close this issue after the next release.

**Comment by JMSwag** [comment] 2019-05-05 00:45
Fixed in [v3.0.0](https://github.com/JMSwag/PyUpdater/releases/tag/3.0.0)

**Closed as completed by JMSwag** 2019-05-05 00:45 UTC

**Comment by jgwinner** [comment] 2021-03-26 18:35
I ran into this - for some reason, on a completely blank project with Python 3.9.2, if I do a:

pip install PyUpdater
or
pip install -U PyUpdater

I get version 2.5.3

I had to stuff the GitHub release URL manually. Yet PyPi.org says version 3.1.1 is the current.

I duplicated this on two boxes. 

Any ideas what the issue is?
